### ISSUE TITLE
Make a Contribution Instruction | README.md

### ISSUE THREAD

**Issue by MindfulLearner** [MindfulLearner/svgestor#12]
The README.md needs a how to contribute Instruction

**Comment by Abhishek022001** [comment]
can i work on this issue?

**Comment by MindfulLearner** [comment]
Yes of course!

**Comment by MindfulLearner** [comment]
still working on it? @Abhishek022001

**Comment by MindfulLearner** [comment]
Thank you! and super good job :) @Abhishek022001 👍🏽
